language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm install ftp-deploy
  - npm install jsftp
  - npm run build
  - npm run publish

notifications:
  email:
    on_failure: change
    on_success: change
