language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run build
  - node deploy.js --host=AZURE_WA_SITE --user=AZURE_WA_USERNAME  --password=AZURE_WA_PASSWORD

notifications:
  email:
    on_failure: change
    on_success: change